name: CI/CD for dlctool

# 触发条件：当代码推送到 master 分支时触发
on:
  push:
    branches:
      - master

jobs:
  # 定义 CI 任务
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install linting tools
        run: |
          python -m pip install black flake8
      - name: Code formatting check
        run: black --check .
      - name: Static code analysis
        run: flake8 --max-line-length=120 .

  # 定义 CD 任务，包含多个针对不同操作系统的构建作业
  cd:
    name: Continuous Deployment
    needs: ci
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: dlctool-linux
            build_command: pyinstaller --onefile dlctool.py && mv dist/dlctool dlctool-linux
          - os: windows-latest
            artifact_name: dlctool-windows.exe
            build_command: pyinstaller --onefile dlctool.py && move dist\dlctool.exe dlctool-windows.exe
          - os: macos-latest
            artifact_name: dlctool-macos
            build_command: pyinstaller --onefile dlctool.py && mv dist/dlctool dlctool-macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pyinstaller
        run: python -m pip install pyinstaller
      - name: Build executable
        run: ${{ matrix.build_command }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  # 定义创建 Release 的任务
  create-release:
    name: Create Release
    needs: cd
    permissions:
      contents: write  # 授予写入内容的权限
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Generate release tag
        id: generate_tag
        run: echo "tag=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          release_name: Release ${{ steps.generate_tag.outputs.tag }}
          body: "Automatically generated release with executables for Linux, Windows, and macOS."
          draft: false
          prerelease: false
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          files: |
            artifacts/*